#!/bin/bash

set -eu

rundir="$(dirname $(readlink -f $0))"
. ${rundir}/helpers/useful.sh

habs_dir=.
source_arg="--source"

usage() {
    cat << EOF
Usage: makeshsrc [options] -- [packages]

Script for building source packages in your HABS dir.

Options:
-h          This help
-a          Build full source packages
-b <dir>    Location of your HABS dir (default .)
EOF
}

buildsrc() {
    msg "Building source in $PWD"
    makepkg "${source_arg}"
}

while getopts hab: opt; do
    case "${opt}" in
        h) usage; exit 0;;
        a) source_arg="--allsource";;
        b) habs_dir="${OPTARG}";;
    esac
done
shift "$((OPTIND - 1))"

for pkg0 in "$@"; do
    pkg1=${pkg0,,}
    [ -d "${habs_dir}/${pkg1}" ] && pkg=${pkg1}
    [ -d "${habs_dir}/haskell-${pkg1}" ] && pkg=haskell-${pkg1}
    if [[ "x${pkg}" != "x" ]]; then
        (cd "${habs_dir}/$pkg"; buildsrc )
    else
        die "No such package: $pkg0"
    fi
    pkg=
done
