#!/usr/bin/env bash

set -eu

rundir="$(dirname $(readlink -f $0))"
. ${rundir}/useful.sh

image_pfx=arch/habs
with_testing=no

usage() {
    cat << EOF
Usage: mkimage-arch.sh [options]

Generate a filesystem for building habs and load it into the local docker

Options:
-h          This help
-n <pfx>    Prefix for name of docker image (default: arch/habs)
-t          Include the testing repo

The image's complete name will be "<pfx>-build".
EOF
}

while getopts ha:n:t opt; do
    case "${opt}" in
        h) usage; exit 0 ;;
        n) image_pfx="${OPTARG}" ;;
        t) with_testing=yes
    esac
done

image_name=${image_pfx}-build

docker build -t ${image_name} docker
