#!/usr/bin/env bash

set -eu

rundir="$(dirname $(readlink -f $0))"
. ${rundir}/helpers/useful.sh

habs_dir=${PWD}
image_pfx="arch/habs"
shell=no
owner_uid=$(id -u)
owner_gid=$(id -g)

usage() {
    cat << EOF
Usage: makeahpkg [options] -- [packages]

Run this script in your HABS dir to build the named packages.

Options:
-h          This help
-u          User to own the built files
-g          Group to own the built files
-b <dir>    Location of your HABS folder (default: .)
-s          Enter a shell instead of building
EOF
exit 0
}

while getopts hu:g:a:s opt; do
    case "${opt}" in
        h) usage; exit 0;;
        u) owner_uid=${OPTARG};;
        g) owner_gid=${OPTARG};;
        s) shell=yes;;
    esac
done
shift $((OPTIND - 1))

image_name=${image_pfx}-build

if [[ "x${shell}" == "xno" ]]; then
    docker_cmd="/usr/bin/bash /habs/helpers/buildpkgs -u ${owner_uid} -g ${owner_gid} -b /habs -- $*"
else
    docker_cmd="/usr/bin/bash -l"
fi

docker run -i -t -v=${habs_dir}:/habs -u habs --env-file /etc/environment \
    ${image_name}:latest \
    ${docker_cmd}
